### ISSUE TITLE
SealError on simple matrix multiplication

### ISSUE THREAD

**Issue by alexander-camuto** [Sunscreen-tech/Sunscreen#165]
Hey all, 

Love the library and have been playing around a bit with it trying to get simple FHE matrix multiplication up and running. As a disclaimer, I am by no means an FHE expert. 

In my setup, I have two square (**DIM x DIM**) matrices **A** and **B** which I am attempting to multiply (**A x B**).  Matrices in this instance are represented as 2-d arrays of (encrypted) Sunscreen types (Signed, Fractional etc...). When both **A** and **B** are encrypted my toy setup works just fine. When **B** is not encrypted the Sunscreen runtime throws : 

`Error: RuntimeError(FheProgramRunError(SealError))`

I've been trying to find the source of this error and it seems to occur when assigning to the individual indices of the multiplication result (`res[row][col]`). Let me know if you are able to replicate it with the code below: 

```rust
use std::time::Instant;
use std::vec::Vec;
use sunscreen::{
    fhe_program,
    types::{bfv::Signed, Cipher},
    Compiler, FheProgramInput, Runtime,
};

const DIM: usize = 2;

/**
 * Naive matrix multiplication
 */
#[fhe_program(scheme = "bfv")]
fn mat_mul_naive(
    a: [[Cipher<Signed>; DIM]; DIM],
    b: [[Signed; DIM]; DIM],
) -> [[Cipher<Signed>; DIM]; DIM] {
    let mut res = a.clone();

    for row in 0..DIM {
        for col in 0..DIM {
            for v in 0..DIM {
                if col == 0 {
                    res[row][col] = a[row][v] * b[v][col];
                } else {
                    res[row][col] = res[row][col] + a[row][v] * b[v][col];
                }
            }
        }
    }
    res
}

/**
 * Creates a matrix and returns it represented as a
 * [`Signed`] type.
 */
fn make_matrix_signed<const M: usize>() -> Result<([[Signed; M]; M]), sunscreen::Error> {
    let mut f_array = [[Signed::default(); M]; M];

    for i in 0..M {
        f_array[i] = (0..M as i64)
            .map(|x| Signed::try_from(x).unwrap())
            .collect::<Vec<Signed>>()
            .try_into()
            .unwrap_or_else(|v: Vec<Signed>| {
                panic!("Expected a Vec of length {} but it was {}", M, v.len())
            });
    }

    Ok(f_array)
}

fn main() -> Result<(), sunscreen::Error> {
    let a_frac = make_matrix_signed::<DIM>()?;

    let b_frac = make_matrix_signed::<DIM>()?;

    let start = Instant::now();

    let app = Compiler::new().fhe_program(mat_mul_naive).compile()?;
    let end = start.elapsed();

    println!("Compiled in {}s", end.as_secs_f64());

    let runtime = Runtime::new(app.params())?;

    let (public_key, private_key) = runtime.generate_keys()?;
    let a_enc = runtime.encrypt(a_frac, &public_key)?;

    let args: Vec<FheProgramInput> = vec![a_enc.clone().into(), b_frac.clone().into()];

    let start = Instant::now();
    let results = runtime.run(app.get_program(mat_mul_naive).unwrap(), args, &public_key)?;
    let end = start.elapsed();

    let fhe_mul: [[Signed; DIM]; DIM] = runtime.decrypt(&results[0], &private_key)?;

    println!("FHE mat mul = {:?} Time: {}s", fhe_mul, end.as_secs_f64());

    Ok(())
}
```

**Comment by rickwebiii** [comment]
We have a  known problem with a lack of clarity when SEAL returns a runtime error and we need to modify SEAL to improve this.

I'm 95% sure you're getting a [transparent ciphertext](https://docs.sunscreen.tech/fhe_programs/writing_an_fhe_program/limitations.html?highlight=transpa#avoid-transparent-ciphertexts). You get this because you have a zero entry in your plaintext matrix. Try changing your range in `make_matrix_signed` to `1..N+1` and see if the problem goes away.

We can offer the ability to allow transparent ciphertexts if people ask for it, but there are security considerations for this. It may be okay if you get a transparent ciphertext in an intermediate computation that gets rolled over as you continue execution, but it's definitely not okay if it's the output of your circuit (they're trivial to detect and decrypt by an observer).

**Comment by alexander-camuto** [comment]
Yup @rickwebiii that was it ! Thank you.
